#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const dataPath = path.join(root, "data.js");
const audioDir = path.join(root, "assets", "audio", "ko");
const manifestPath = path.join(root, "audio-manifest.js");
const voice = process.env.KKOMAKIDS_TTS_VOICE || "Yuna";
const rate = process.env.KKOMAKIDS_TTS_RATE || "145";

function loadData() {
  const code = fs.readFileSync(dataPath, "utf8");
  const context = {};
  vm.createContext(context);
  vm.runInContext(
    `${code}
    Object.assign(this, {
      HANGUL_CONSONANTS,
      HANGUL_VOWELS,
      WORD_PAIRS,
      WORDS,
      SYLLABLE_HINTS,
      SYLLABLE_WORDS,
      COMPLETION_PUZZLES,
      ALL_CONSONANTS,
      ALL_VOWELS,
      ALL_FINALS
    });`,
    context
  );
  return context;
}

function audioKeyForText(text) {
  return Array.from(String(text).normalize("NFC"))
    .map(ch => ch.codePointAt(0).toString(16))
    .join("-");
}

function decomposeSyllable(data, s) {
  const code = s.charCodeAt(0) - 0xAC00;
  if (code < 0 || code > 11171) return null;
  const finalIdx = code % 28;
  const consonantIdx = Math.floor(code / 588);
  const vowelIdx = Math.floor((code % 588) / 28);
  return {
    consonant: data.ALL_CONSONANTS[consonantIdx],
    vowel: data.ALL_VOWELS[vowelIdx],
    final: data.ALL_FINALS[finalIdx],
    hasFinal: finalIdx !== 0,
  };
}

function consonantName(c) {
  const names = {
    "ㄱ": "기역", "ㄴ": "니은", "ㄷ": "디귿", "ㄹ": "리을", "ㅁ": "미음",
    "ㅂ": "비읍", "ㅅ": "시옷", "ㅇ": "이응", "ㅈ": "지읒", "ㅊ": "치읓",
    "ㅋ": "키읔", "ㅌ": "티읕", "ㅍ": "피읖", "ㅎ": "히읗",
  };
  return names[c] || c;
}

function collectSpeechItems(data) {
  const items = new Set();
  const add = text => {
    const normalized = String(text || "").trim().normalize("NFC");
    if (normalized) items.add(normalized);
  };

  [...data.HANGUL_CONSONANTS, ...data.HANGUL_VOWELS].forEach(item => {
    add(item.name);
    add(item.word);
    add(`${item.name}, ${item.word}`);
  });

  data.WORDS.forEach(item => add(item.ko));
  data.WORD_PAIRS.forEach(item => {
    add(item.word);
    add(`${item.word} 찾아 터뜨려요`);
    add(`${item.word} 잡아요`);

    const initial = decomposeSyllable(data, item.word[0])?.consonant;
    if (initial) {
      add(`${item.word}처럼 ${consonantName(initial)} 소리로 시작하는 단어 잡아요`);
    }
  });

  data.SYLLABLE_WORDS.forEach(item => {
    add(item.word);
    Array.from(item.word).forEach(ch => add(ch));
  });

  data.COMPLETION_PUZZLES.forEach(item => {
    add(item.word);
    Array.from(item.word).forEach(ch => add(ch));
  });

  Object.entries(data.SYLLABLE_HINTS).forEach(([syllable, item]) => {
    add(syllable);
    add(item.word);
  });

  const consonants = new Set(
    data.WORD_PAIRS
      .map(item => decomposeSyllable(data, item.word[0])?.consonant)
      .filter(Boolean)
  );
  consonants.forEach(c => add(`${consonantName(c)}이 들어간 단어 잡아요`));

  return [...items].sort((a, b) => a.localeCompare(b, "ko"));
}

function generateAudio(text, filePath) {
  const result = spawnSync("say", [
    "-v", voice,
    "-r", rate,
    "--file-format=m4af",
    "-o", filePath,
    text,
  ], { stdio: "pipe", encoding: "utf8" });

  if (result.status !== 0) {
    throw new Error(`say failed for "${text}": ${result.stderr || result.stdout}`);
  }
}

function writeManifest(items) {
  const keys = items.map(audioKeyForText).sort();
  const body = `// Auto-generated by scripts/generate-audio.js.
window.KKOMAKIDS_KO_AUDIO_KEYS = new Set(${JSON.stringify(keys, null, 2)});
`;
  fs.writeFileSync(manifestPath, body);
}

function main() {
  const data = loadData();
  const items = collectSpeechItems(data);
  fs.mkdirSync(audioDir, { recursive: true });

  let created = 0;
  let skipped = 0;
  items.forEach(text => {
    const filePath = path.join(audioDir, `${audioKeyForText(text)}.m4a`);
    if (fs.existsSync(filePath) && !process.argv.includes("--force")) {
      skipped++;
      return;
    }
    generateAudio(text, filePath);
    created++;
  });

  writeManifest(items);
  console.log(`Korean audio items: ${items.length}`);
  console.log(`Created: ${created}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Voice: ${voice}, rate: ${rate}`);
}

main();
